name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: desplegar
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://jenkinslorenzo.daw2.pve2.fpmislata.com"
        user: "system_builder"
        token: "116942501779617363dbf3281a1ab26ae9"
        job: "Desplegar"
