name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: desplegar
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: Gympass/jenkins-job-action@0.0.5
      with:
        jenkins_url: "http://jenkinslorenzo.daw2.pve2.fpmislata.com"
        jenkins_user: "system_builder"
        jenkins_token: ${{ secrets.TOKEN }}
        job_name: "Desplegar"
